name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'
      - name: Build with Maven
        run: mvn clean verify
      - name: List coverage report files
        run: ls -la target/site/jacoco/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

